### ISSUE TITLE
The `MagickWand.annotateImage` is throwing an exception

### ISSUE THREAD

**Issue by carloseustaquio** [cherryleafroad/kmagick#1]
The method is throwing an error by just trying to use it..

```sh
E/AndroidRuntime: FATAL EXCEPTION: Thread-4
    Process: com.example.youtubemusicshare, PID: 14748
    com.cherryleafroad.kmagick.MagickWandException: `MagickWand::annotateImage()` threw an exception : unable to annotate image
        at com.cherryleafroad.kmagick.MagickWand.annotateImage(Native Method)
        at com.example.youtubemusicshare.MainActivity.createPostImage(MainActivity.kt:107)
        at com.example.youtubemusicshare.MainActivity.handleGetPostData$lambda-0(MainActivity.kt:69)
        at com.example.youtubemusicshare.MainActivity.$r8$lambda$TQdY_LSuJYvORw4FAJGdesrt8A8(Unknown Source:0)
        at com.example.youtubemusicshare.MainActivity$$ExternalSyntheticLambda0.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:920)
I/Process: Sending signal. PID: 14748 SIG: 9
```

I'm trying to use the exact same code of the example https://github.com/cherryleafroad/kmagick/blob/main/example/src/com/example/cli/Main.kt

```kt
        Magick.initialize().use {
            Log.i(TAG, "magick initialized")
            val wand = MagickWand()

            val pw = PixelWand()
            pw.color = "#ff0000"
            wand.newImage(500, 500, pw)

            val dwand = DrawingWand()
            dwand.fontSize = 40.0
            dwand.font = "Times New Roman"

            val colorWand = PixelWand()
            colorWand.color = "black"
            dwand.fillColor = colorWand
            wand.annotateImage(DrawingWand(), 1.0,50.0, 1.0, "Sometext")
        }
```

**Comment by cherryleafroad** [comment]
Example works perfectly on Windows. I'll check on Android once I get that set up

**Comment by cherryleafroad** [comment]
Judging by the [function in the underlying API bindings](https://github.com/nlfiedler/magick-rust/blob/a035544a96b8327ab6a8510d1a4c3e90674f9548/src/wand/magick.rs#L100), this isn't a fault in my library. What happened is that imagemagick itself is throwing you the error for some reason (who knows).

Can you please [run `MagickWand.getException()`](https://github.com/cherryleafroad/kmagick/blob/8bd75c4bb90990f1af703a26531eb73027ba7d05/src/main/kotlin/com/cherryleafroad/kmagick/MagickWand.kt#L87) to find out what it is? You'll get back a [nice data class](https://github.com/cherryleafroad/kmagick/blob/main/src/main/kotlin/com/cherryleafroad/kmagick/NativeMagickException.kt) with an exception type and message. You can look up the code in [ExceptionType](https://github.com/cherryleafroad/kmagick/blob/main/src/main/kotlin/com/cherryleafroad/kmagick/ExceptionType.kt) to see which one it is.

**Comment by cherryleafroad** [comment]
Just want to update you. The reason it fails is because the font isn't available. (The Exception message I showed above will tell you that as well)

**Comment by carloseustaquio** [comment]
Hey @cherryleafroad, thank you so much for the support! I did a workaround using the native Android Canvas, and it worked well... The project where I`m using this lib is paused right now, but I'll probably be trying the solution you proposed in the future.

**Comment by cherryleafroad** [comment]
I've updated a lot of the examples and instructions to make it clearer how to handle and check the errors when they do occur. That should help you in the future :)
