### ISSUE TITLE
Can I use Kmagic lib. with MultiThreading?

### ISSUE THREAD

**Issue by MudssirAhmed** [cherryleafroad/kmagick#8]

**Comment by cherryleafroad** [comment]
There should be no problem using it with multithreading, although it hasn't been extensively tested either. I tested it once with no known issues. If for some strange reason there is an issue though, report it here.

**Comment by cherryleafroad** [comment]
Closing due to no input. If this is still a question, feel free to make a new comment or post in the discussion section.
